name: Linux Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  buildLinux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: latest
      - name: Setup Haxe
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null --quiet
          chmod +x docs/setup/setup.sh
          sh docs/setup/setup.sh
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compiling for Linux
        run: haxelib run lime build Project.xml linux
      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Linux
          path: 'export/release/linux/bin'
